name: point2mesh
channels:
  - pytorch
  - nvidia
  - fvcore
  - iopath
  - conda-forge
dependencies:
  - python=3.9
  - pytorch=1.13.0
  - torchvision
  - pytorch-cuda=11.6
  - fvcore
  - iopath
  - pip
  - pip:
    - "git+https://github.com/facebookresearch/pytorch3d.git@stable"